variable "project_id" {
  description = "GCP project ID to deploy into."
  type        = string
}

variable "region" {
  description = "GCP region for all resources."
  type        = string
  default     = "asia-southeast2" # Jakarta — closest to DOKU/ION's Indonesian user base.
}

variable "image_tag" {
  description = "Tag applied to all images by scripts/build-and-push.sh (e.g. a git SHA). Terraform ignores image changes after first create — see lifecycle blocks."
  type        = string
  default     = "latest"
}

variable "artifact_registry_repo_id" {
  description = "Artifact Registry Docker repository ID."
  type        = string
  default     = "insurance-app"
}

# --- Cloud SQL ---

variable "postgres_tier" {
  description = "Cloud SQL machine tier. db-f1-micro is the cheapest shared-core tier, fine for a demo app."
  type        = string
  default     = "db-f1-micro"
}

variable "sql_deletion_protection" {
  description = "Set true once this stops being a throwaway test deployment."
  type        = bool
  default     = false
}

variable "db_name_bap" {
  type    = string
  default = "insurance_bap"
}

variable "db_name_bpp" {
  type    = string
  default = "insurance_bpp"
}

variable "db_user" {
  type    = string
  default = "insurance"
}

# --- Redis ---

variable "redis_tier" {
  type    = string
  default = "BASIC" # no HA — this is a test app, matches the single redis:alpine container today.
}

variable "redis_memory_size_gb" {
  type    = number
  default = 1
}

# --- Secrets ---
# No variables here on purpose. The Postgres password is auto-generated by
# Terraform (see secrets.tf's random_password resource). Every other secret
# (bpp-jwt-secret, doku-client-id, doku-secret-key, the onix signing keys) is
# created as an empty Secret Manager container by Terraform, then seeded with
# its actual value by you, once, via scripts/seed-secrets.sh — see
# terraform/README.md. This keeps plaintext secrets out of any
# Terraform-visible file, including .tfvars.

# --- DOKU settlement bank account IDs (identifiers, not secrets — kept as plain vars) ---
# NOTE: the original docker-compose.yml sets DOKU_ION_BANK_ACCOUNT_ID to a DIFFERENT
# value on ion-service (BNK-0010-...) vs on bpp (BNK-0003-...). That mismatch is
# preserved here via two separate variables rather than silently "fixed" — verify
# with whoever owns the DOKU sandbox setup which one is actually correct.

variable "doku_bpp_bank_account_id" {
  type    = string
  default = "BNK-0002-1782383276041"
}

variable "doku_bap_bank_account_id" {
  type    = string
  default = "BNK-0001-1782383221155"
}

variable "doku_ion_bank_account_id_on_ion_service" {
  type    = string
  default = "BNK-0010-1782548213200"
}

variable "doku_ion_bank_account_id_on_bpp" {
  type    = string
  default = "BNK-0003-1782383300000"
}
